### ISSUE TITLE
[FEAT] Entity 생성 및 H2 메모리디비 테스트

### ISSUE THREAD

**Issue by isayaksh** [isayaksh/pingpong#1]
# ✏️ Description
Entity를 생성하고, 테이블 생성 과정에 문제가 없는지 테스트한다.

# 🛠 Features

### User
```
- id : integer
- fakerId : integer
- name : string
- email : string
- status : string
  - WAIT(대기), ACTIVE(활성), NON_ACTIVE(비활성)
- created_at : datetime
- updated_at : datetime
```

### Room
```
- id : integer
- title : string
- host : integer
  - User.id
- room_type : string
  - SINGLE(단식), DOUBLE(복식)
- status : string
  - WAIT(대기), PROGRESS(진행중), FINISH(완료)
- created_at : datetime
- updated_at : datetime
```

### UserRoom
```
- id : integer
- room_id : integer
- user_id : integer
- team : string
  - RED, BLUE
```

---

## application.yml
```
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:pingpongdb  # 인메모리 H2 DB 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시 테이블 자동 생성
    show-sql: true  # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true  # SQL 예쁘게 출력
```
